# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    data_dir: '%kernel.project_dir%/data'

services:
   _defaults:
      public: false
      autowire: true

   # makes classes in src/ available to be used as services
   # this creates a service per class whose id is the fully-qualified class name
   App\:
      resource: '%kernel.project_dir%/src/*'
      exclude: '%kernel.project_dir%/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
   App\Controller\:
      resource: '../src/Controller'
      tags: ['controller.service_arguments']

   _instanceof:
      App\Game\Loader\LoaderInterface:
          tags: ['game.loader']

   App\Game\WordList:
      arguments:
          - ['%data_dir%/words.txt','%data_dir%/words.xml']
      calls:
          - ['setLoaders', [!tagged 'game.loader']]

   #game_runner: '@App\Game\Runner' alias peu flexible
   game_runner:
      alias: 'App\Game\Runner'
      public: true

   usersignup_handler:
      alias: 'App\User\Handler\UserSignupHandler'
      public: true